version: '3'

dotenv: ['./.env']

vars:
  IMAGE_REPO: "{{.USER}}/stackstate-k8s-ext"
  VERSION: 0.0.4

tasks:
  docker-build:
    cmds:
      - docker build . -t {{.IMAGE_REPO}}:{{.VERSION}}
  docker-push:
    cmds:
      - echo $PASSWORD | docker login -u {{.USER}} --password-stdin
      - docker push {{.IMAGE_REPO}}:{{.VERSION}}
